version: '2'
services:
  spring:
    image: walhamanel/manelwalha-5sae1-g2
    ports:
      - "9002:9002"
    depends_on:
      - mysql  
  mysql:
    image: walhamanel/mysql_image
    environment:
      MYSQL_ROOT_HOST: '%'  
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
