version: '2'
services:
  spring:
    image: walhamanel/manelwalha-5sae1-g2
    ports:
      - "9002:9002"
    depends_on:
      - mysql  
    networks:
      - app-network
  mysql:
    image: walhamanel/mysql_image
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin2
      - MYSQL_ROOT_HOST='%'  
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
