version: '2'
services:
  mysql:
    image: walhamanel/mysql_image
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin2
      MYSQL_ROOT_HOST: '%'  
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - custom_network
      
  spring:
    image: walhamanel/manelwalha-5sae1-g2
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/foyer?createDatabaseIfNotExist=true
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin2
    depends_on:
      - mysql  
    networks:
      - custom_network
  
networks:
  custom_network:
    driver: bridge
